---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: checking for install at {{ suonobuoy_install_exe }}
  become: true
  stat:
    path: '{{ sonobuoy_install_exe }}'
  changed_when: false
  register: sonobuoy_binary
- when: not sonobuoy_binary.stat.exists
  block:
    - name: downloading {{ sonobuoy_url }} to {{ sonobuoy_tmp_tgz }}
      become: true
      become_user: root
      get_url:
        url: '{{ sonobuoy_url }}'
        dest: '{{ sonobuoy_tmp_tgz }}'
        mode: 0644
        checksum: '{{ sonobuoy_checksum }}'
    - name: mkdir -p {{ sonobuoy_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ sonobuoy_install_dir }}'
        mode: 0755
        state: directory
    - name: unarchiving {{ sonobuoy_tmp_tgz }} to {{ sonobuoy_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ sonobuoy_tmp_tgz }}'
        dest: '{{ sonobuoy_install_dir }}'
        creates: '{{ sonobuoy_install_exe }}'
  always:
    - name: rm -f {{ sonobuoy_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ sonobuoy_tmp_tgz }}'
        state: absent
- name: linking {{ sonobuoy_install_link }} to {{ sonobuoy_install_exe }}
  become: true
  become_user: root
  file:
    src: '{{ sonobuoy_install_exe }}'
    dest: '{{ sonobuoy_install_link }}'
    state: link
