---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Checking for install at {{ suonobuoy_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ sonobuoy_install_exe }}'
  changed_when: false
  register: sonobuoy_binary
- name: Downloading and installing sonobuoy
  when: not sonobuoy_binary.stat.exists
  block:
    - name: Downloading {{ sonobuoy_url }} to {{ sonobuoy_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ sonobuoy_url }}'
        dest: '{{ sonobuoy_tmp_tgz }}'
        mode: '644'
        checksum: '{{ sonobuoy_checksum }}'
    - name: Mkdir -p {{ sonobuoy_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ sonobuoy_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchiving {{ sonobuoy_tmp_tgz }} to {{ sonobuoy_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ sonobuoy_tmp_tgz }}'
        dest: '{{ sonobuoy_install_dir }}'
        creates: '{{ sonobuoy_install_exe }}'
  always:
    - name: Rm -f {{ sonobuoy_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ sonobuoy_tmp_tgz }}'
        state: absent
- name: Linking {{ sonobuoy_install_link }} to {{ sonobuoy_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ sonobuoy_install_exe }}'
    dest: '{{ sonobuoy_install_link }}'
    state: link
